services:
  postgres:
    image: diegodataengineer/postgres:1.0.1
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - 5442:5432
    volumes:
      - ./postgres/data-postgres:/var/lib/postgresql/data
      - ./postgres:/util
      - ./scripts:/scripts
    # restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s


######################################################
# MINIO SERVICE
######################################################
  minio:
    image: diegodataengineer/minio-s3-v1.0.0
    container_name: minio
    command:  server --console-address ":9001" /data
    ports:
     - "9050:9000"
     - "9051:9001"
    hostname: minio
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: admin
      MINIO_ACCESS_KEY: datalake
      MINIO_SECRET_KEY: datalake
      GLUE_ID: "294463638235"
    volumes:
      - ./minio/data1:/data
      - ./minio/minio-setup.sh:/minio-setup.sh
      - ./scripts:/scripts
    entrypoint: /bin/bash -c "/usr/local/bin/minio server /data --console-address :9001 & /minio-setup.sh && wait"
    # restart: always

######################################################
# HIVE SERVICES
######################################################

  hive:
    image: diegodataengineer/hive-v1.0.0
    container_name: hive
    environment:
      AWS_ACCESS_KEY_ID: datalake
      AWS_SECRET_ACCESS_KEY: datalake
      HIVE_CUSTOM_CONF_DIR: "/hive_custom_conf"
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://metastore:9083"
      IS_RESUME: "true"
      #HIVE_VERSION: "3.1.3"
    ports:
       - "10000:10000"
       - "10002:10002"
    depends_on:
        - hive-metastore
    user: root
    volumes:
       - ./hive/conf:/hive_custom_conf
       - ./hive:/util
    # restart: always

  hive-metastore:
    hostname: metastore
    image: diegodataengineer/hive-metastore-v1.0.0
    container_name: metastore
    environment:
      AWS_ACCESS_KEY_ID: datalake
      AWS_SECRET_ACCESS_KEY: datalake
      HIVE_CUSTOM_CONF_DIR: "/hive_custom_conf"
      SERVICE_NAME: metastore
      IS_RESUME: "true"
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=admin -Djavax.jdo.option.ConnectionPassword=admin"
    ports:
       - "9083:9083"
    depends_on:
      - postgres
    user: root
    volumes:
       - ./hive/meta:/opt/hive/data/warehouse
       - ./hive/conf:/hive_custom_conf
       - ./hive:/util
    # restart: always

  emr-local:
    image: diegodataengineer/emr-local:1.0.0
    container_name: emr-local
    hostname: emr-local
    ports:
      - "2222:2222"
    depends_on:
      - namenode
      #- metastore
    user: root
    volumes:
      - ./spark/util:/util
      - ./interface:/interface
    # restart: always

  namenode:
    image: diegodataengineer/namenode-v1.0.0
    container_name: namenode
    hostname: namenode
    volumes:
      - ./hadoop/hdfs/namenode/name:/hadoop/dfs/name
      - ./hadoop/hdfs/namenode/edits:/hadoop/dfs/edits
      - ./hadoop/util:/util
    env_file:
       - ./hadoop/hadoop.env
    ports:
      - "9870:9870"
    # restart: always
    deploy:
      resources:
        limits:
          memory: 500m

  datanode:
    image: diegodataengineer/datanode-v1.0.0
    container_name: datanode
    hostname: datanode
    volumes:
      - ./hadoop/hdfs/datanode/data:/hadoop/dfs/data
      - ./hadoop/util:/util
    env_file:
      - ./hadoop/hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    # restart: always
    deploy:
      resources:
        limits:
          memory: 500m

  trino:
    image: trino-doido
    container_name: trino
    hostname: trino
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      #- metastore
    user: root
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/conf:/conf
      - ./scripts:/scripts
    # restart: always


